### ISSUE TITLE
Missing throws clause

### ISSUE THREAD

**Issue by TheWizz** [digitalpetri/modbus#13]
I just updated to the latest version. When I tried to run the Tcp Master example, the compiler complained about an unhandled exception originating from the sharedEventLoop().shutdownGracefully().get(); call in the com.digitalpetri.modbus.codec.Modbus#releaseSharedResources. Indeed, java.util.concurrent.Future#get is declared as throwing InterruptedException, ExecutionException.

I fixed it by adding the same throws clause to releaseSharedResources(), like this.

```
    /** Shutdown/stop any shared resources that may be in use. */
    public static void releaseSharedResources() throws ExecutionException, InterruptedException {
        sharedExecutor().shutdown();
        sharedEventLoop().shutdownGracefully().get();
        sharedWheelTimer().stop();
    }

```
 If you agree that's the correct fix, you may want to do likewise.

-JM

**Comment by kevinherron** [comment]
Ooops, that I what I get for merging a harmless looking PR without actually testing it 🙄 

Thanks, I'll get it fixed.
