### ISSUE TITLE
ERROR com.digitalpetri.modbus.examples.master.ReadCoilsMaster - Completed exceptionally, message=functionCode=ReadCoils, exceptionCode=IllegalFunction

### ISSUE THREAD

**Issue by allon3721** [digitalpetri/modbus#15]
ModbusTcpMasterConfig config = new ModbusTcpMasterConfig.Builder("localhost").build();
ModbusTcpMaster master = new ModbusTcpMaster(config);

        CompletableFuture<ReadCoilsResponse> future =
                master.sendRequest(new ReadCoilsRequest(0, 2), 0);

future.thenAccept(response -> {
   ByteBuf coilStatus = response.getCoilStatus();

    ReferenceCountUtil.release(response);
});

**Comment by kevinherron** [comment]
`IllegalFunction` typically means whatever slave you're talking to hasn't implemented the function code you're trying to use.
