### ISSUE TITLE
How to configure the server slave id

### ISSUE THREAD

**Issue by pintify** [digitalpetri/modbus#16]
I have followed the simple slave configuration and been working on improving it towards my project needs. However I have been unable to configure the slave ID, how can it be done? I am trying to achieve that the slave does not answer when the slave ID does not match the one I am requesting.

**Comment by kevinherron** [comment]
Check `ServiceRequest#getUnitId` in your handler. Unit ID and Slave ID are the same thing.

**Comment by pintify** [comment]
Oh, OK, I was looking for that on configuration time, instead of in the handler. Anyway, it worked perfectly. Thank you!

**Comment by kevinherron** [comment]
👍
