### ISSUE TITLE
where could I store per connection variables?

### ISSUE THREAD

**Issue by galoko** [digitalpetri/modbus#17]
where could I store per connection variables? I mean lets picture the situation: device connects to my slave server, write multiple registers and then read holding registers, I generate values in holding registers based on written registers values. So where exactly should I keep these values in-between of onWriteMultipleRegisters and onReadHoldingRegisters calls? I'm kinda out of options here or so it seems

**Comment by kevinherron** [comment]
I'm not sure what you mean you're out of options... you have infinite options. I purposely do not implement any kind of process/register map abstraction because everyone's use case is different.

Put them in a `Map<Integer, Integer>` or get as complicated as you'd like?

**Comment by kevinherron** [comment]
Modbus register and coil values are not traditionally per-connection - it's supposed to be a global address space.
