### ISSUE TITLE
Question: Will this work for Android?

### ISSUE THREAD

**Issue by DanielMartensson** [digitalpetri/modbus#25]
Hi!

Nice library. Will this work for Android?

Best regards 
Daniel

**Comment by kevinherron** [comment]
I don't know. It's built for JDK 8. Did Android ever get `CompletableFuture`?

**Comment by DanielMartensson** [comment]
> I don't know. It's built for JDK 8. Did Android ever get `CompletableFuture`?

Hi. I haven't tested it. Perhaps I will give it a try.
