### ISSUE TITLE
Consider upgrading netty to 4.1.x ？

### ISSUE THREAD

**Issue by jobmission** [digitalpetri/modbus#26]
Hello kevinherron!

Other components of my project depend on netty 4.1, but this repository depends on netty 4.0, netty conflicts.
Consider upgrading netty to 4.1.x ？

**Comment by kevinherron** [comment]
Agreed, my other projects are using Netty 4.1.x as well. I will upgrade it before 1.2.0 is released.

**Comment by kevinherron** [comment]
Done, will get released eventually.
