### ISSUE TITLE
Release version 1.2.0

### ISSUE THREAD

**Issue by Ashiiro** [digitalpetri/modbus#33]
Hello,

Are you planning soon to release the version "1.2.0.RELEASE" ?

The latest version i could find is 1.1.1.

Thank you for this project,
Ashi

**Comment by kevinherron** [comment]
Sure, I can release that today. I didn’t realize it had been so long.

**Comment by Ashiiro** [comment]
Did you release it on the official maven central or any other repository ?

**Comment by kevinherron** [comment]
Sorry I dropped the ball on this. I've released it just now, it should be available in Maven Central within the hour.
