### ISSUE TITLE
How to read data in batches

### ISSUE THREAD

**Issue by 17802592576** [digitalpetri/modbus#36]
I just started using this project, and I'm very confused about how to read data in batches. If you can, please guide me to complete this code.

**Comment by kevinherron** [comment]
Batching of data like you mention in your email[1] is a "higher level" operation not implemented by this library.

I'm not familiar with how modbus4j works, but I assume this is some function that takes a list of register address + datatype (mapped over multiple 16-bit registers if necessary) and "optimize" it into a group of requests that would cover all the registers needed.

[1] ![image](https://user-images.githubusercontent.com/340273/113714487-49f8b500-969d-11eb-82f4-02547165d59b.png)

**Comment by 17802592576** [comment]
Thank you very much for your response, I will try other ways to slove this problem.My best to you.

**Comment by iotclouddeveloper** [comment]
> Thank you very much for your response, I will try other ways to slove this problem.My best to you.

I also have this question，How did you solve it
