### ISSUE TITLE
How to use raw requests and responses?

### ISSUE THREAD

**Issue by huangxianyi** [digitalpetri/modbus#58]
For example:
Request: 30 03 00 00 00 05 81 E8
Response: 30 03 0A 00 00 00 00 00 02 00 00 00 20 1F DF

**Comment by kevinherron** [comment]
No support for such a thing, but perhaps in the next version of the library I'm working on there can be some kind of support for sending "raw" PDUs, at least for Modbus TCP.

**Comment by huangxianyi** [comment]
> No support for such a thing, but perhaps in the next version of the library I'm working on there can be some kind of support for sending "raw" PDUs, at least for Modbus TCP.
Can I convert the  "raw" request to a ModbusRequest? Like "30 03 00 00 00 05 81 E8" to ReadHoldingRegistersRequest .
