### ISSUE TITLE
java.util.function.Consumer

### ISSUE THREAD

**Issue by yanzixiang** [digitalpetri/modbus#7]
Error:Gradle: ModbusTcpSlave.java:110-111: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Consumer

i got this error.

**Comment by kevinherron** [comment]
You may need to try something like retrolambda to get this library working on Android:

https://github.com/orfjackal/retrolambda
https://github.com/evant/gradle-retrolambda
