### ISSUE TITLE
How to get "CD AB" order from ByteBuf?

### ISSUE THREAD

**Issue by vbnetvbnet** [digitalpetri/modbus#8]
How can I get a "CD AB" ordered float from ByteBuf? Like:
![image](https://cloud.githubusercontent.com/assets/19724257/21072317/d0260a96-bef8-11e6-840c-8139a124ba57.png)

I know very little about modbus. Can you please help me? Thanks.

**Comment by kevinherron** [comment]
I'm not sure what that software would consider the order to be by default (maybe DC BA), but try something like this:

```java
short cd = Short.reverseBytes(buffer.readShort());
short ab = Short.reverseBytes(buffer.readShort());
float f = Float.intBitsToFloat(cd << 16 | ab);
```

Assuming the buffer contains at least 4 bytes (meaning you read at least 2 registers, because each register is 16-bit).

**Comment by vbnetvbnet** [comment]
@kevinherron Thank you for your reply. I'm trying using your code, but I got the value equal to order BA DC rather than DC BA. Is it because of different default order?

**Comment by kevinherron** [comment]
Maybe this then?

```java
short ab = buffer.readShort();
short cd = buffer.readShort();
float f = Float.intBitsToFloat((cd << 16 | ab));
```

**Comment by vbnetvbnet** [comment]
It works! Thanks!
