### ISSUE TITLE
Support for modbus serial ?

### ISSUE THREAD

**Issue by jvelo** [digitalpetri/modbus#9]
Any interest in supporting modbus serial ?

I could give it a try - at least for the RTU flavor.

Thanks

**Comment by kevinherron** [comment]
I've been planning it for a while. Hoping to implement it this week, actually...

**Comment by jvelo** [comment]
Wow, that's great :)

If that can be of any help, I'm available for feedback / testing in the field

**Comment by kevinherron** [comment]
Hey, still planning on doing this, and yes I'd like your feedback and testing when it's done :)

I'll update this when something is ready. This week hasn't been as "free" as I thought it would be...

**Comment by awindillman** [comment]
RTU would be a nice addition.  Would recommend/request purejavacomm (https://github.com/nyholku/purejavacomm) for the serial implementation.  Alternatives (RX/TX or Sun's old one) are not "pure" java and are, at best, outdated.

**Comment by kevinherron** [comment]
Yep, still working on it, slowly. Doing it as a version 2.0.0 because it involves major package and module shuffling. I'm planning on using PureJavaComm for the serial implementation.

**Comment by shubhamkumargupta** [comment]
Hey, @kevinherron, have you released the support for ModBus Serial? I'm not able too find the RTU support in this repository.

**Comment by kevinherron** [comment]
No progress since last comment, but I'll need it for work in the coming months so I suspect that'll force it to get finished.

**Comment by madisonleavo** [comment]
@kevinherron How goes serial implementation? do you want to commit to branch if any of us can help?

**Comment by casmeiron** [comment]
Hey @kevinherron, I'm too interested on this... ModbusSerial RTU would be gr8! Maybe we can all help you so it can be released sooner. How it goes?

**Comment by shubhamkumargupta** [comment]
Hey @casmeiron, we @hashmapinc has developed the Modbus_RTU you can take a look at the forked repo : [](https://github.com/hashmapinc/modbus)

**Comment by casmeiron** [comment]
Thanks very much I will take a look into that!

Best Regards.

**Comment by jaysonjh** [comment]
Hey @kevinherron, have you released the support for ModBus Serial? I'm not able find the RTU support in this repository？

**Comment by kevinherron** [comment]
No, sorry, it never happened. I keep putting it off because the pressure to implement it for use at work went away. I do still plan to do it, but in the meantime you'll have to use some other library if you need RTU/serial support.

**Comment by kevinherron** [comment]
Done for 2.0, now available on `master` branch.
