### ISSUE TITLE
Even when TCP connection is dropped

### ISSUE THREAD

**Issue by TheWizz** [digitalpetri/modbus#91]
I see there's an isConnected() method on ModbusTcpMaster to poll for connection status. I would prefer some kind of event or notification when the TCP connection is lost, but haven't found any. Am I overlloking something, or is polling isConnected() every now and then the preferred method?

Mike

**Comment by kevinherron** [comment]
This was merged, just hasn't been released yet: https://github.com/digitalpetri/modbus/pull/78

**Comment by TheWizz** [comment]
Excellent! Any ETA on when this may be released into the wild?

**Comment by kevinherron** [comment]
I'll try to release this evening, should have done it a couple weeks ago but I forgot.

**Comment by kevinherron** [comment]
@TheWizz [released](https://github.com/digitalpetri/modbus/releases/tag/v2.0.1) and available in Maven Central any minute.

**Comment by TheWizz** [comment]
Many thanks!
